### ISSUE TITLE
BoNeMEAL + BanManager 7: Trying to get property 'uuid' of non-object

### ISSUE THREAD

**Issue by Sir-Will** [ftbastler/BoNeMEAL#109]
Several /admin sites return the `Trying to get property 'uuid' of non-object` error.
Sites like Active Punishments, All Notes...

```
Trying to get property 'uuid' of non-object (View: /bans/application/resources/views/admin/activePunishments.blade.php)
```

php 7.2
BanManager 7.0.4

**Comment by oranges13** [comment]
Ah yeah, Ban Manager 7 changed the database schema quite a bit and I have not had a chance to look at any of those changes. I know they modified the UUID field for one, which is why you are receiving this error.

Did you recently upgrade BanManager?

**Comment by Sir-Will** [comment]
Yes, I also reinstalled bonemeal.

**Comment by oranges13** [comment]
Reinstalling Bonemeal will not help at this juncture because it does not support the changes made in BanManager 7.

I also don't believe that we can have versions that support both banmanager < 7 and banmanager 7+ due to the schema changes.

At this time you will need to downgrade BanManager (which due to the schema changes probably won't be possible) or not use BoneMEal until it is upgraded, pending the rewrite.

**Comment by oranges13** [comment]
Hey @Sir-Will 

I had a chance to test this with my current installation of bonemeal as-is and our server that just upgraded to Ban Manager 7.1.

I cannot replicate the issue that you're describing. Any chance that you have more detailed debug logs to help?
