### ISSUE TITLE
Error while installing application: Trying to access array offset on value of type int

### ISSUE THREAD

**Issue by RemixFusion** [ftbastler/BoNeMEAL#112]
I'm attempting to install BoNeMEAL at the URL below: https://bans.megacrafting.com/BoNeMEAL/index.php/install/run

Once I get to entering in a username/password and continuing, I receive this error message:
Error while installing application: Trying to access array offset on value of type int

Please go back and try again or report this bug to our issue tracker.

We are using PHP7.4, and have loaded in the SQLITE extension.

**Comment by oranges13** [comment]
The version of Laravel this uses may not be compatible with 7.4.

I can dig into this deeper soon but in the meanwhile can you try with 7.2 or 7.3?

Also is it possible for you to post a recent log? These can be found in `storage/logs` or your Apache logs.

**Comment by RemixFusion** [comment]
We have 7.4 configured for this and a few other virtual hosts on our system, I did try switching but had issues with other virtual hosts when I did that.

storage/logs is empty... and here's my Apache2 log.
`HP Warning:  PHP Startup: Unable to load dynamic library 'pdo_mysql' (tried: /usr/lib/php/20190902/pdo_mysql (/usr/lib/php/20190902/pdo_mysql: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/pdo_mysql.so (/usr/lib/php/20190902/pdo_mysq>
[Fri Jul 24 17:10:51.066265 2020] [mpm_prefork:notice] [pid 443431] AH00163: Apache/2.4.41 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/1.1.1f configured -- resuming normal operations
[Fri Jul 24 17:10:51.066313 2020] [core:notice] [pid 443431] AH00094: Command line: '/usr/sbin/apache2'
[Fri Jul 24 17:13:38.867361 2020] [mpm_prefork:notice] [pid 443431] AH00169: caught SIGTERM, shutting down
[Fri Jul 24 17:13:38.994985 2020] [mpm_prefork:notice] [pid 443682] AH00163: Apache/2.4.41 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/1.1.1f configured -- resuming normal operations
[Fri Jul 24 17:13:38.995030 2020] [core:notice] [pid 443682] AH00094: Command line: '/usr/sbin/apache2'
[Fri Jul 24 17:13:56.291227 2020] [php7:error] [pid 443695] [client 141.101.69.236:15054] script '/var/www/html/xmlrpc.php' not found or unable to stat`

**Comment by oranges13** [comment]
You also need the `pdo_mysql` extension enabled or it cannot communicate with the remote server.

Try enabling that and try again?

**Comment by RemixFusion** [comment]
It's enabled per: https://bans.megacrafting.com/BoNeMEAL/php.php

**Comment by jwindfelder** [comment]
I'm also having the same problem. I've tried enabling pdo_mysql and still same problem.

**Comment by jwindfelder** [comment]
For anyone who has the same error. I changed my PHP version from 7.4 to 5.5 and I did not receive this error. If you don't want to keep your web server at 5.5 you can set it back to the latest version AFTER the initial setup. However @oranges13 there must be something wrong with the way BoNeMEAL is using PHP.

**Comment by oranges13** [comment]
It's old, so yes. Like I said in a previous comment I'm guessing it's a lack of compatability with 7.4 as that's much newer than the version of Laravel this is running on was designed for.

It runs on 7.2 at least but I have not actively tested on 7.3+

Can you try 7.2? That should keep you in some security updates rather than going back to the stone age.

**Comment by oranges13** [comment]
@CoryLuba @Windy315 I just confirmed this with a quick docker install. This is an issue with Artisan and php 7.4 and this version of Laravel.

PHP 7.3 confirmed working, so that should give you a middle ground of modernity and functionality until I can rewrite the software! I'm going to continue to test and see if upgrading to a slightly newer version of Laravel doesn't involve too much work. I'm stuck between keeping this version limping along and rewriting it so it's compatible with new versions of PHP going forward.

Hey thanks for these reports, I really appreciate it!
